name: scalewrite
description: A Flutter app for offline-first work order management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # State management (stay on 2.x for Phase 1)
  flutter_riverpod: ^2.6.1

  # Maps (patch bumps only)
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0

  # Location & permissions
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Core utils
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  uuid: ^4.0.0
  intl: ^0.20.2
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  path: ^1.8.3
  collection: ^1.18.0
  http: ^1.2.2

  # Drift database (safe minor upgrades)
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Codegen & Drift dev (safe minor upgrades)
  build_runner: ^2.8.0
  drift_dev: ^2.28.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/test_data.json
    - assets/images/
    - assets/seed_inventory_items.json
