name: scalewrite_v2
description: A Flutter app for offline-first work order management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  geolocator: ^10.0.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  uuid: ^4.0.0
  intl: ^0.18.1

  # Drift database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.16.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/test_data_fixed.json
