name: scalewrite_v2
description: A Flutter app for offline-first work order management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  uuid: ^4.0.0
  intl: ^0.20.2
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  path: ^1.8.3
  collection: ^1.18.0

  # Drift database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.16.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/test_data.json
    - assets/images/
    - assets/seed_inventory_items.json